name: Build & Publish

on:
  push:
    branches: ["master", "accept", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore
        run: dotnet restore ./PatientAPI.sln

      - name: Build
        run: dotnet build ./PatientAPI.sln --configuration Release --no-restore

  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Image Name
        id: set-image-name
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "::set-output name=tag::dev"
          elif [[ "${{ github.ref }}" == "refs/heads/accept" ]]; then
            echo "::set-output name=tag::accept"
          else
            echo "::set-output name=tag::latest"
          fi
        shell: bash

      - name: Build and Push Docker Image
        run: |
          docker buildx build --file Dockerfile -t ${{ steps.set-image-name.outputs.tag }} .
          docker push ${{secrets.DOCKER_USERNAME}}/patientapi:${{ steps.set-image-name.outputs.tag }}
        env:
          DOCKER_CLI: docker
